
const STATIONS=[
{id:1,code:'EDR-KIM-01',name:'Fernur Sözen MTAL',theme:'Kimya Her Yerde'},
{id:2,code:'EDR-KIM-02',name:'Edremit İlçe Halk Kütüphanesi',theme:'Atomların Hikâyesi'},
{id:3,code:'EDR-KIM-03',name:'Faruk Serpil Parkı',theme:'Element Avcısı'},
{id:4,code:'EDR-KIM-04',name:'Ayşe Sıdıka Erke Etnografya Müzesi',theme:'Maddenin Geçmişi'},
{id:5,code:'EDR-KIM-05',name:'Edremit MYO',theme:'Zeytinin Kimyası'},
{id:6,code:'EDR-KIM-06',name:'Sarıkız Meydanı',theme:'Denizin Kimyasal Şifresi'},
{id:7,code:'EDR-KIM-07',name:'Zeytinyağı Analiz Laboratuvarı',theme:'Gerçek Hayatta Kimyasal Analiz'},
{id:8,code:'EDR-KIM-08',name:'Arıtma Tesisi / Aday İstasyon',theme:'Suyun Kimyası'},
{id:9,code:'EDR-KIM-09',name:'Şehit Hamdibey Meydanı',theme:'Kimya Büyük Final Şifresi'},
{id:10,code:'EDR-KIM-10',name:'Fernur Sözen MTAL',theme:'Final'}
];
let state=JSON.parse(localStorage.getItem('edremitKimyaState')||'null')||{team:null,completed:[],evidence:[],wrongAttempts:0};
let mediaStream=null,scanTimer=null,deferredPrompt=null,selectedTile=null;
const $=id=>document.getElementById(id); const views=[...document.querySelectorAll('.view')];
function save(){localStorage.setItem('edremitKimyaState',JSON.stringify(state));}
function showView(id){views.forEach(v=>v.classList.add('hidden'));$(id).classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'});if(id!=='scannerView')stopCamera();}
function render(){const hasTeam=!!state.team;$('teamSetup').classList.toggle('hidden',hasTeam);$('dashboard').classList.toggle('hidden',!hasTeam);if(hasTeam){$('dashTeamName').textContent=state.team.name;const c=state.completed.length;$('progressBadge').textContent=`${c} / 10`;$('progressBar').style.width=`${c*10}%`;renderRoles();}renderStations();renderEvidence();renderAchievement();}
function saveTeam(){const vals=[$('teamName').value.trim(),$('member1').value.trim(),$('member2').value.trim(),$('member3').value.trim()];if(vals.some(v=>!v)){ $('teamError').classList.remove('hidden'); return; }state.team={name:vals[0],members:vals.slice(1)};save();render();$('teamError').classList.add('hidden');}
function roleNames(stationNo=1){const m=state.team?.members||['Öğrenci 1','Öğrenci 2','Öğrenci 3'];const shift=(stationNo-1)%3;const arr=[m[(0+shift)%3],m[(1+shift)%3],m[(2+shift)%3]];return {chemist:arr[0],navigator:arr[1],documenter:arr[2]};}
function renderRoles(){const next=Math.min(state.completed.length+1,10);const r=roleNames(next);$('roleList').innerHTML=`<div class="role">🧪 <b>Kimyager:</b> ${r.chemist}</div><div class="role">🧭 <b>Navigatör:</b> ${r.navigator}</div><div class="role">📸 <b>Belgeleyici:</b> ${r.documenter}</div>`;}
function renderStations(){$('stationList').innerHTML=STATIONS.map(s=>{const done=state.completed.includes(s.id);const unlocked=s.id===1||state.completed.includes(s.id-1);return `<div class="stationItem"><b>${done?'✅':unlocked?'🔓':'🔒'} ${s.id}. ${s.name}</b><br><span class="${done?'statusDone':'statusLocked'}">${done?'Tamamlandı':unlocked?'Erişilebilir':'Kilitli'}</span><div class="muted small">${s.theme}</div></div>`;}).join('');}
function renderEvidence(){$('evidenceList').innerHTML=STATIONS.map(s=>{const done=state.evidence.includes(s.id);return `<div class="evidenceItem"><b>${done?'📸✅':'📷'} İstasyon ${s.id}</b> — ${s.name}<br><span class="${done?'statusDone':'statusLocked'}">${done?'Fotoğraf görevi işaretlendi':'Henüz tamamlanmadı'}</span></div>`;}).join('');}
function renderAchievement(){const c=state.completed.length;if(c===10){$('titleStatus').textContent='Edremit Kimya Kâşifi';$('achievementText').textContent='Parkurun tüm istasyonlarını tamamladınız.';}else{$('titleStatus').textContent='Edremit Kimya Kâşifi Adayı';$('achievementText').textContent=`${c}/10 istasyon tamamlandı. Unvan için parkurun tamamını bitirin.`;}}
function openStationByCode(raw){const code=(raw||'').trim().toUpperCase();const s=STATIONS.find(x=>x.code===code);if(!s){showScanError('Bu kod parkura ait görünmüyor.');return;}const unlocked=s.id===1||state.completed.includes(s.id-1);if(!unlocked){showScanError(`İstasyon ${s.id} henüz kilitli.`);return;}stopCamera();showView('stationView');document.querySelectorAll('.station').forEach(x=>x.classList.add('hidden'));if(s.id===1){$('station01').classList.remove('hidden');renderStation1();}else{$('stationPlaceholder').classList.remove('hidden');$('placeholderTitle').textContent=`İstasyon ${String(s.id).padStart(2,'0')} — ${s.name}`;}}
function showScanError(msg){$('scanError').textContent=msg;$('scanError').classList.remove('hidden');}
function renderStation1(){const r=roleNames(1);$('stationRoles').innerHTML=`<div class="role">🧪 <b>Kimyager:</b> ${r.chemist}</div><div class="role">🧭 <b>Navigatör:</b> ${r.navigator}</div><div class="role">📸 <b>Belgeleyici:</b> ${r.documenter}</div>`;ensurePreview();if(localStorage.getItem('s1QuestionSolved')==='yes'){$('puzzleCard').classList.remove('hidden');initPuzzle();}}
function bindQuestion(){document.querySelectorAll('#s1Question .answer').forEach(btn=>{btn.addEventListener('click',()=>{const ok=btn.dataset.correct==='true';if(ok){btn.classList.add('good');$('answerFeedback').innerHTML='<div class="successBox">✅ <b>Kimya kilidi açıldı.</b> Kimya; maddelerin yapısını, özelliklerini ve geçirdiği değişimleri inceler.</div>';localStorage.setItem('s1QuestionSolved','yes');setTimeout(()=>{$('puzzleCard').classList.remove('hidden');initPuzzle();$('puzzleCard').scrollIntoView({behavior:'smooth'});},400);}else{state.wrongAttempts=(state.wrongAttempts||0)+1;save();btn.classList.add('bad');const hint=state.wrongAttempts===1?'Kimya yalnızca laboratuvardaki tepkimeleri değil; maddelerin yapısını, özelliklerini ve değişimlerini de inceler.':'Paslanma, temizlik maddesi ve plastik malzeme üçü de farklı yönlerden kimyayla ilişkilidir.';$('answerFeedback').innerHTML=`<div class="hintBox">🔒 Hedef henüz açılmadı.<br>💡 ${hint}</div>`;}});});}
const mapSVG=`<svg xmlns="http://www.w3.org/2000/svg" width="900" height="900" viewBox="0 0 900 900"><defs><linearGradient id="bg" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#f7f0e4"/><stop offset="1" stop-color="#f3ead9"/></linearGradient></defs><rect width="900" height="900" fill="url(#bg)"/><g fill="#cfe7c9"><circle cx="150" cy="230" r="64"/><circle cx="660" cy="730" r="58"/><circle cx="790" cy="140" r="44"/></g><g stroke="#cebfa8" stroke-width="40" fill="none" stroke-linecap="round"><path d="M30 150 C240 120 490 200 860 125"/><path d="M55 370 C260 330 540 390 865 340"/><path d="M35 610 C270 555 520 650 860 585"/><path d="M205 35 C245 250 245 570 215 870"/><path d="M505 35 C505 255 550 570 535 870"/><path d="M760 35 C735 245 755 575 790 870"/></g><g stroke="#fff" stroke-width="11" fill="none" stroke-linecap="round"><path d="M30 150 C240 120 490 200 860 125"/><path d="M55 370 C260 330 540 390 865 340"/><path d="M35 610 C270 555 520 650 860 585"/><path d="M205 35 C245 250 245 570 215 870"/><path d="M505 35 C505 255 550 570 535 870"/><path d="M760 35 C735 245 755 575 790 870"/></g><g font-family="Arial" fill="#2d434d"><text x="65" y="110" font-size="34" font-weight="700">Cennetayağı Mah.</text><text x="548" y="300" font-size="30" transform="rotate(-4 548 300)">İstasyon Cd.</text><text x="82" y="738" font-size="27">6021 Sk.</text></g><g transform="translate(95 650)"><rect width="250" height="130" rx="22" fill="#0b4f6c"/><text x="125" y="48" text-anchor="middle" font-family="Arial" font-size="32" fill="#fff" font-weight="700">OKUL</text><text x="125" y="84" text-anchor="middle" font-family="Arial" font-size="22" fill="#d7f1ff">Başlangıç</text><text x="125" y="109" text-anchor="middle" font-family="Arial" font-size="18" fill="#d7f1ff">Fernur Sözen MTAL</text></g><path d="M345 690 C460 630 540 505 655 385" stroke="#148255" stroke-width="14" fill="none" stroke-dasharray="22 16"/><g transform="translate(648 238)"><path d="M72 0C32 0 0 32 0 72c0 57 72 136 72 136s72-79 72-136C144 32 112 0 72 0z" fill="#e3454f"/><circle cx="72" cy="70" r="26" fill="white"/><text x="72" y="80" text-anchor="middle" font-family="Arial" font-size="36" font-weight="700" fill="#e3454f">2</text></g><g transform="translate(572 115)"><rect width="210" height="84" rx="16" fill="#ffffffcc" stroke="#d9d9d9"/><text x="105" y="34" text-anchor="middle" font-family="Arial" font-size="24" font-weight="700" fill="#21343d">HEDEF 02</text><text x="105" y="61" text-anchor="middle" font-family="Arial" font-size="18" fill="#415962">İstasyon Caddesi</text></g></svg>`;
const mapURI='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(mapSVG); let puzzleOrder=[...Array(9).keys()];
function ensurePreview(){const c=$('mapPreview');if(c.childElementCount===0){const img=document.createElement('img');img.src=mapURI;img.alt='Harita önizleme';c.appendChild(img);}}
function makeTile(idx){const div=document.createElement('div');div.className='tile';div.dataset.correct=idx;const img=document.createElement('img');const x=(idx%3)*300,y=Math.floor(idx/3)*300;const tileSVG=`<svg xmlns="http://www.w3.org/2000/svg" width="300" height="300" viewBox="${x} ${y} 300 300"><image href="${mapURI}" width="900" height="900"/></svg>`;img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(tileSVG);const num=document.createElement('div');num.className='tileNum';num.textContent=idx+1;div.appendChild(img);div.appendChild(num);div.addEventListener('click',()=>tileClick(div));return div;}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}}
function initPuzzle(){const board=$('puzzle');board.innerHTML='';board.classList.remove('puzzleSolved');selectedTile=null;puzzleOrder=[...Array(9).keys()];shuffle(puzzleOrder);if(puzzleOrder.every((v,i)=>v===i))[puzzleOrder[0],puzzleOrder[1]]=[puzzleOrder[1],puzzleOrder[0]];puzzleOrder.forEach(i=>board.appendChild(makeTile(i)));$('target02').classList.add('hidden');$('photoMission').classList.add('hidden');$('puzzleHintBox').classList.add('hidden');}
function tileClick(el){if(!selectedTile){selectedTile=el;el.classList.add('selected');return;}if(selectedTile===el){el.classList.remove('selected');selectedTile=null;return;}const board=$('puzzle'),nodes=[...board.children],a=nodes.indexOf(selectedTile),b=nodes.indexOf(el);if(a<b){board.insertBefore(el,selectedTile);board.insertBefore(selectedTile,nodes[b+1]||null);}else{board.insertBefore(selectedTile,el);board.insertBefore(el,nodes[a+1]||null);}selectedTile.classList.remove('selected');selectedTile=null;checkPuzzle();}
function checkPuzzle(){const ok=[...$('puzzle').children].every((el,i)=>Number(el.dataset.correct)===i);if(ok){$('puzzle').classList.add('puzzleSolved');$('target02').classList.remove('hidden');$('photoMission').classList.remove('hidden');localStorage.setItem('s1PuzzleSolved','yes');setTimeout(()=>{$('target02').scrollIntoView({behavior:'smooth',block:'start'});},180);}}
function previewPhoto(file){if(!file)return;const url=URL.createObjectURL(file);$('photoPreview').innerHTML=`<img src="${url}" alt="Fotoğraf önizleme">`;$('photoPreview').classList.remove('hidden');}
function completeStation1(){if(!$('photoDone').checked){$('completeError').classList.remove('hidden');return;}$('completeError').classList.add('hidden');if(!state.completed.includes(1))state.completed.push(1);if(!state.evidence.includes(1))state.evidence.push(1);save();render();alert('🏁 İstasyon 01 tamamlandı! Hedef 02 artık erişilebilir.');showView('homeView');}
async function startCamera(){$('scanError').classList.add('hidden');if(!navigator.mediaDevices?.getUserMedia){$('cameraNote').textContent='Bu tarayıcı kamera erişimini desteklemiyor. Manuel kod girişini kullanın.';return;}try{mediaStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});$('video').srcObject=mediaStream;await $('video').play();$('startCameraBtn').classList.add('hidden');$('stopCameraBtn').classList.remove('hidden');if('BarcodeDetector' in window){const detector=new BarcodeDetector({formats:['qr_code']});$('cameraNote').textContent='Kamera açık. QR kodu çerçeveye getirin.';scanTimer=setInterval(async()=>{try{const codes=await detector.detect($('video'));if(codes?.length)openStationByCode(codes[0].rawValue);}catch(e){}},700);}else{$('cameraNote').textContent='Tarayıcı otomatik QR algılamıyor. Kodu manuel girebilirsiniz.';}}catch(e){$('cameraNote').textContent='Kamera izni alınamadı. Siteyi GitHub Pages üzerinden HTTPS ile açtığınızdan emin olun.';}}
function stopCamera(){if(scanTimer){clearInterval(scanTimer);scanTimer=null}if(mediaStream){mediaStream.getTracks().forEach(t=>t.stop());mediaStream=null}if($('video'))$('video').srcObject=null;$('startCameraBtn')?.classList.remove('hidden');$('stopCameraBtn')?.classList.add('hidden');}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden');});$('installBtn').addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installBtn').classList.add('hidden');});
async function copyTargetAddress(){
  const address='Edremit İlçe Halk Kütüphanesi — Cennetayağı Mahallesi, İstasyon Caddesi No:14, Edremit / Balıkesir';
  try{
    await navigator.clipboard.writeText(address);
  }catch(e){
    const ta=document.createElement('textarea');
    ta.value=address;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();
  }
  if($('copyStatus')){
    $('copyStatus').classList.remove('hidden');
    setTimeout(()=>$('copyStatus').classList.add('hidden'),2500);
  }
}
$('saveTeamBtn').addEventListener('click',saveTeam);$('scanBtn').addEventListener('click',()=>showView('scannerView'));$('routeBtn').addEventListener('click',()=>showView('routeView'));$('evidenceBtn').addEventListener('click',()=>showView('evidenceView'));$('achievementsBtn').addEventListener('click',()=>showView('achievementsView'));document.querySelectorAll('[data-back]').forEach(b=>b.addEventListener('click',()=>showView('homeView')));$('startCameraBtn').addEventListener('click',startCamera);$('stopCameraBtn').addEventListener('click',stopCamera);$('manualOpenBtn').addEventListener('click',()=>openStationByCode($('manualCode').value));$('shuffleBtn').addEventListener('click',initPuzzle);$('hintBtn').addEventListener('click',()=>$('puzzleHintBox').classList.toggle('hidden'));$('togglePreviewBtn').addEventListener('click',()=>$('mapPreview').classList.toggle('hidden'));$('photoInput').addEventListener('change',e=>previewPhoto(e.target.files[0]));$('completeStation1Btn').addEventListener('click',completeStation1);$('copyAddressBtn')?.addEventListener('click',copyTargetAddress);bindQuestion();render();if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));}
